module.exports = {
  ERR_ID_NOT_EXISTING: "id not existing",
  ERR_EMAIL_NOT_EXISTING: "email not existing",
  ERR_ID_IS_INCORRECTED: "id is incorrect",
  ERR_EMAIL_REGISTERED_VERIFIED: "email already registered and verified",
  ERR_EMAIL_REGISTERED_UNVERIFIED: "email already registered and unverified",
  ERR_ID_NOT_FOUND: "id not found",
  ERR_ADMIN_CAN_DO: "only admin can do",
  ERR_INTERNAL_SERVER_ERROR: "internal server error",
  ERR_PAYLOAD_EMPTY: "No payload sent",
  ERR_PARAMS_EMPTY: "No params sent",
  ERR_COMPANY_ALREADY_EXIST: "This company name already registered",
  ERR_EMAIL_REGISTERED_BLOCKED:"Email already registered but blocked",
  ERR_INCORRECT_CREDENTIALS: "incorrect credentials",
  ERR_SUBSCRIPTION_EXPIRED: "your subscription plan has been expired",
  ERR_NO_OF_TRIES_EXCEEDED:"number of tries for login ended, kindly reset password",
  ERR_DEACTIVE:"this echo de-active",
  ERR_INVALID_URL: "this url is invalid",
  ERR_OLD_PASSWORD_NOT_MATCH:"Old password does not match",
  ERR_WENT_WRONG:"Something went wrong",
  ERR_SIGN_INVALID: "Signature invalid",
  ERR_USER_NOT_FOUND: "user not found",
  ERR_AUTH_KEY: "authKey not found",
  ERR_INCCORRECT_OTP: "incorrect otp",
  ERR_OTP_EXPIRED: "otp expired",
  ERR_INCORRECT_EXPIRED_OTP: "incorrect otp or otp expired",
  ERR_USER_NOT_REGISTERED: "user not found, kindly register",
  ERR_SITEADMIN_NOT_FOUND: "Site admin not found",
  ERR_UNABLE_TO_UPDATE_SITE_ADMIN: "Unable to update site admin",
  ERR_UNABLE_TO_SEND_REPORT: "Unable to sent requested report",
  ERR_MISSING_PARAMS: "Missing Params",
  ERR_ANNOUNCEMNT_UPDATE: "Unable to update announcement",
  ERR_SITENAME_EXIST:"Site Name already exist",
  ERR_EMAIL_EXIST: "Email already exist"
};
