module.exports = {
  SUCC_LOGIN: "login successfully",
  SUCC_UPDATE: "updated successfully",
  SUCC_CREATE: "created successfully",
  SUCC_DELETE: "deleted successfully",
  SUCC_LOADED: "retrieve successfully",
  SUCC_SAVE: "saved successfully",
  SUCC_BLOCK: "blocked successfully",
  SUCC_REJECT: "rejected successfully",
  SUCC_ACCEPT: "accepted successfully",
  SUCC_ACTIVE: "activated successfully",
  SUCC_INACTIVE: "inactivated successfully",
  SUCC_SEND_MAIL: "sended mail successfully",
  SUCC_FOLLOW: "followed successfully",
  SUCC_SENT: "sent successfully",
  SUCC_SENT_OTP: "otp sent successfully",
  VERIFIED: "verified",
  UNVERIFIED: "unverified",
  BLOCKED: "blocked",
  RESETPASSWORD: "resetPassword",
  WRONGPASSWORD: "wrongPassword",
  SUCC_STATUS_PASSWORD_CHANGED:"changed password",
  SUCC_CHANGE_PASSWORD:"Password changed successfully",
  SUCC_PDF_SENT: "send pdf file successfully",
  SUCC_PAYMENT_CAPTURED: "payment captured successfully",
  SUCC_SIGN_VALID:"Signature valid",
  SUCC_OTP_VERIFIED: "otp verified successfully"
};
